apiVersion: v1
kind: Service
metadata:
  name: java-devsecops-demo-svc
  namespace: java-devsecops
  labels:
    app: java-devsecops-demo
spec:
  type: NodePort
  selector:
    app: java-devsecops-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
